#! /bin/sh

bspc monitor DVI-D-0  -d I II III-Music IV-Code V-Browser
bspc monitor HDMI-0   -d VI

bspc config click_to_focus        true
bspc config pointer_follows_focus true

bspc config border_width          0
bspc config window_gap            8

bspc config top_padding           15
bspc config bottom_padding        10
bspc config right_padding         10
bspc config left_padding          10

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Gimp state=floating follow=on
#bspc rule -a tilda  state=floating layer=below locked